version: '3'
services:
  fnserver:
    restart: always
    image: fnproject/fnserver
    ports:
      - "8080:8080"
    environment:
      FN_LOGSTORE_URL: "s3://<DO_SPACE_KEY>:<DO_SPACE_SECRET>@<DO_SPACE_ENDPOINT>/<DO_SPACE_REGION>/<DO_SPACE_NAME>?ssl=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  fnserver-ui:
    depends_on:
      - fnserver
    image: fnproject/ui
    restart: always
    ports:
      - "4000:4000"
    links:
      - "fnserver"
    environment:
      - FN_API_URL=http://fnserver:8080